
    create table authorities (
       id integer generated by default as identity,
        authority varchar(255),
        username varchar(255),
        primary key (id)
    )

    create table deliveries (
       id integer generated by default as identity,
        creation_date timestamp not null,
        description varchar(255),
        download_url varchar(255),
        team_id integer not null,
        primary key (id)
    )

    create table invitations (
       id integer generated by default as identity,
        creation_date timestamp not null,
        status integer not null,
        team_id integer not null,
        user_username varchar(255) not null,
        primary key (id)
    )

    create table jam_resource (
       id integer generated by default as identity,
        description varchar(255),
        download_url varchar(255),
        jams_id integer not null,
        primary key (id)
    )

    create table jams (
       id integer generated by default as identity,
        description varchar(255),
        difficulty integer not null check (difficulty>=1 AND difficulty<=5),
        end timestamp not null,
        inscription_deadline timestamp not null,
        max_team_size integer not null check (max_team_size>=1),
        max_teams integer not null check (max_teams>=2),
        min_teams integer not null check (min_teams>=2),
        name varchar(255),
        rated boolean not null,
        start timestamp not null,
        creator_username varchar(255) not null,
        winner_id integer,
        primary key (id)
    )

    create table marks (
       id integer generated by default as identity,
        comments varchar(255),
        value float not null check (value<=10 AND value>=0),
        judge_username varchar(255) not null,
        team_id integer not null,
        primary key (id)
    )

    create table teams (
       id integer generated by default as identity,
        creation_date timestamp not null,
        name varchar(255),
        jam_id integer not null,
        primary key (id)
    )

    create table teams_members (
       team_id integer not null,
        members_username varchar(255) not null,
        primary key (team_id, members_username)
    )

    create table users (
       username varchar(255) not null,
        email varchar(255),
        enabled boolean not null,
        password varchar(255),
        phone_area_code varchar(255),
        phone_country_code integer not null check (phone_country_code>=1 AND phone_country_code<=999),
        phone_number varchar(255),
        primary key (username)
    )

    alter table deliveries 
       add constraint FKcss5qvkkvpasro5e1rthragdc 
       foreign key (team_id) 
       references teams

    alter table invitations 
       add constraint FK1m1usbedadl51q5ea4vic07nv 
       foreign key (team_id) 
       references teams

    alter table invitations 
       add constraint FKektgsaitdaq535cgm3e2aklf9 
       foreign key (user_username) 
       references users

    alter table invitations 
       add constraint FKh02uji0cu6q99wu56ct1ej7gr 
       foreign key (id) 
       references invitations

    alter table jam_resource 
       add constraint FK7o4wqem412rdioeoglakfq8sf 
       foreign key (jams_id) 
       references jams

    alter table jams 
       add constraint FK41tnpsmpgf6skrgnij87uqthu 
       foreign key (creator_username) 
       references users

    alter table jams 
       add constraint FKke4hpil1bywpdert9kiwu4p5v 
       foreign key (winner_id) 
       references teams

    alter table marks 
       add constraint FKdcmy25ywalirrtr3ekwrf1li3 
       foreign key (judge_username) 
       references users

    alter table marks 
       add constraint FK3uhe65linb0gr6qcki943du3x 
       foreign key (team_id) 
       references teams

    alter table teams 
       add constraint FKd572y86aviiut58qquf94dtps 
       foreign key (jam_id) 
       references jams

    alter table teams_members 
       add constraint FKnmv0pgv8hhu7hyd1to9vr9nbu 
       foreign key (members_username) 
       references users

    alter table teams_members 
       add constraint FK4pucaacixk5i6dae9jx6c9hj4 
       foreign key (team_id) 
       references teams

    create table authorities (
       id integer generated by default as identity,
        authority varchar(255),
        username varchar(255),
        primary key (id)
    )

    create table deliveries (
       id integer generated by default as identity,
        creation_date timestamp not null,
        description varchar(255),
        download_url varchar(255),
        team_id integer not null,
        primary key (id)
    )

    create table invitations (
       id integer generated by default as identity,
        creation_date timestamp not null,
        status integer not null,
        team_id integer not null,
        user_username varchar(255) not null,
        primary key (id)
    )

    create table jam_resource (
       id integer generated by default as identity,
        description varchar(255),
        download_url varchar(255),
        jams_id integer not null,
        primary key (id)
    )

    create table jams (
       id integer generated by default as identity,
        description varchar(255),
        difficulty integer not null check (difficulty>=1 AND difficulty<=5),
        end timestamp not null,
        inscription_deadline timestamp not null,
        max_team_size integer not null check (max_team_size>=1),
        max_teams integer not null check (max_teams>=2),
        min_teams integer not null check (min_teams>=2),
        name varchar(255),
        rated boolean not null,
        start timestamp not null,
        creator_username varchar(255) not null,
        winner_id integer,
        primary key (id)
    )

    create table marks (
       id integer generated by default as identity,
        comments varchar(255),
        value float not null check (value<=10 AND value>=0),
        judge_username varchar(255) not null,
        team_id integer not null,
        primary key (id)
    )

    create table teams (
       id integer generated by default as identity,
        creation_date timestamp not null,
        name varchar(255),
        jam_id integer not null,
        primary key (id)
    )

    create table teams_members (
       team_id integer not null,
        members_username varchar(255) not null,
        primary key (team_id, members_username)
    )

    create table users (
       username varchar(255) not null,
        email varchar(255),
        enabled boolean not null,
        password varchar(255),
        phone_area_code varchar(255),
        phone_country_code integer not null check (phone_country_code<=999 AND phone_country_code>=1),
        phone_number varchar(255),
        primary key (username)
    )

    alter table deliveries 
       add constraint FKcss5qvkkvpasro5e1rthragdc 
       foreign key (team_id) 
       references teams

    alter table invitations 
       add constraint FK1m1usbedadl51q5ea4vic07nv 
       foreign key (team_id) 
       references teams

    alter table invitations 
       add constraint FKektgsaitdaq535cgm3e2aklf9 
       foreign key (user_username) 
       references users

    alter table invitations 
       add constraint FKh02uji0cu6q99wu56ct1ej7gr 
       foreign key (id) 
       references invitations

    alter table jam_resource 
       add constraint FK7o4wqem412rdioeoglakfq8sf 
       foreign key (jams_id) 
       references jams

    alter table jams 
       add constraint FK41tnpsmpgf6skrgnij87uqthu 
       foreign key (creator_username) 
       references users

    alter table jams 
       add constraint FKke4hpil1bywpdert9kiwu4p5v 
       foreign key (winner_id) 
       references teams

    alter table marks 
       add constraint FKdcmy25ywalirrtr3ekwrf1li3 
       foreign key (judge_username) 
       references users

    alter table marks 
       add constraint FK3uhe65linb0gr6qcki943du3x 
       foreign key (team_id) 
       references teams

    alter table teams 
       add constraint FKd572y86aviiut58qquf94dtps 
       foreign key (jam_id) 
       references jams

    alter table teams_members 
       add constraint FKnmv0pgv8hhu7hyd1to9vr9nbu 
       foreign key (members_username) 
       references users

    alter table teams_members 
       add constraint FK4pucaacixk5i6dae9jx6c9hj4 
       foreign key (team_id) 
       references teams

    create table authorities (
       id integer generated by default as identity,
        authority varchar(255),
        username varchar(255),
        primary key (id)
    )

    create table deliveries (
       id integer generated by default as identity,
        creation_date timestamp not null,
        description varchar(255),
        download_url varchar(255),
        team_id integer not null,
        primary key (id)
    )

    create table invitations (
       id integer generated by default as identity,
        creation_date timestamp not null,
        status integer not null,
        team_id integer not null,
        user_username varchar(255) not null,
        primary key (id)
    )

    create table jam_resource (
       id integer generated by default as identity,
        description varchar(255),
        download_url varchar(255),
        jams_id integer not null,
        primary key (id)
    )

    create table jams (
       id integer generated by default as identity,
        description varchar(255),
        difficulty integer not null check (difficulty>=1 AND difficulty<=5),
        end timestamp not null,
        inscription_deadline timestamp not null,
        max_team_size integer not null check (max_team_size>=1),
        max_teams integer not null check (max_teams>=2),
        min_teams integer not null check (min_teams>=2),
        name varchar(255),
        rated boolean not null,
        start timestamp not null,
        creator_username varchar(255) not null,
        winner_id integer,
        primary key (id)
    )

    create table marks (
       id integer generated by default as identity,
        comments varchar(255),
        value float not null check (value<=10 AND value>=0),
        judge_username varchar(255) not null,
        team_id integer not null,
        primary key (id)
    )

    create table teams (
       id integer generated by default as identity,
        creation_date timestamp not null,
        name varchar(255),
        jam_id integer not null,
        primary key (id)
    )

    create table teams_members (
       team_id integer not null,
        members_username varchar(255) not null,
        primary key (team_id, members_username)
    )

    create table users (
       username varchar(255) not null,
        email varchar(255),
        enabled boolean not null,
        password varchar(255),
        phone_area_code varchar(255),
        phone_country_code integer not null check (phone_country_code<=999 AND phone_country_code>=1),
        phone_number varchar(255),
        primary key (username)
    )

    alter table deliveries 
       add constraint FKcss5qvkkvpasro5e1rthragdc 
       foreign key (team_id) 
       references teams

    alter table invitations 
       add constraint FK1m1usbedadl51q5ea4vic07nv 
       foreign key (team_id) 
       references teams

    alter table invitations 
       add constraint FKektgsaitdaq535cgm3e2aklf9 
       foreign key (user_username) 
       references users

    alter table invitations 
       add constraint FKh02uji0cu6q99wu56ct1ej7gr 
       foreign key (id) 
       references invitations

    alter table jam_resource 
       add constraint FK7o4wqem412rdioeoglakfq8sf 
       foreign key (jams_id) 
       references jams

    alter table jams 
       add constraint FK41tnpsmpgf6skrgnij87uqthu 
       foreign key (creator_username) 
       references users

    alter table jams 
       add constraint FKke4hpil1bywpdert9kiwu4p5v 
       foreign key (winner_id) 
       references teams

    alter table marks 
       add constraint FKdcmy25ywalirrtr3ekwrf1li3 
       foreign key (judge_username) 
       references users

    alter table marks 
       add constraint FK3uhe65linb0gr6qcki943du3x 
       foreign key (team_id) 
       references teams

    alter table teams 
       add constraint FKd572y86aviiut58qquf94dtps 
       foreign key (jam_id) 
       references jams

    alter table teams_members 
       add constraint FKnmv0pgv8hhu7hyd1to9vr9nbu 
       foreign key (members_username) 
       references users

    alter table teams_members 
       add constraint FK4pucaacixk5i6dae9jx6c9hj4 
       foreign key (team_id) 
       references teams
